### ISSUE TITLE
SNMP Error

### ISSUE THREAD

**Issue by polikit** [CygnusNetworks/check_ruckus_vsz#1]
Hi, when I tried to start check_ruckus_vsz it gives me an error:

 **RUCKUSVSZ UNKNOWN: RuntimeError: Cannot query oid %r if multiple varBinds keys are present**

Debian 9.4

**Comment by cygnusb** [comment]
Do you have package python-pysnmp4-mibs installed?
Which version is your Ruckus VSZ? 
Most possibly some of the MIBs are not matching the installed VSZ Version

**Comment by polikit** [comment]
Yes, I have python-pysnmp4-mibs and te version of VSZ is 3.2.1.0.193.

**Comment by cygnusb** [comment]
Ok, thanks. Can you please run with -vvvv and provide the output?

**Comment by polikit** [comment]
RUCKUSVSZ UNKNOWN: RuntimeError: Cannot query oid %r if multiple varBinds keys are present
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 43, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/check_ruckus_vsz-0.10-py2.7.egg/EGG-INFO/scripts/check_ruckus_vsz", line 399, in main
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 120, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 128, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/platform/posix.py", line 19, in with_timeout
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 117, in run
    check()
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 105, in __call__
    self._evaluate_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 79, in _evaluate_resource
    for metric in metrics:
  File "/usr/local/lib/python2.7/dist-packages/check_ruckus_vsz-0.10-py2.7.egg/EGG-INFO/scripts/check_ruckus_vsz", line 120, in probe
  File "build/bdist.linux-x86_64/egg/ruckus_vsz_snmp/snmpclient.py", line 320, in get_value
    return self.get_by_dict(oid)
  File "build/bdist.linux-x86_64/egg/ruckus_vsz_snmp/snmpclient.py", line 301, in get_by_dict
    raise RuntimeError("Cannot query oid %r if multiple varBinds keys are present")
RuntimeError: Cannot query oid %r if multiple varBinds keys are present
Probing Ruckus SCG device 10.0.2.250 through SNMP
Queried Ruckus SCG device 10.0.2.250 through SNMP - device is reachable
Found Sysname vsz-sbz-01 and sysdescr SmartCell Gateway
Starting SNMP polling of host 10.0.2.250

**Comment by cygnusb** [comment]
Your installed VSZ is rather old and it seems ruckus changed the MIBs. So your VSZ Version is not compatible
